name: run-behave-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bdd-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BDD tests and generate HTML report
        run: |
          behave -f behave_html_formatter:HTMLFormatter -o results-reports/report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: behave-html-report
          path: results-reports/report.html
